DEEPSORT:
  REID_CKPT: "yolov9/deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.7
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  MIN_AGE: 10
  N_INIT: 3
  NN_BUDGET: 100
  
